package com.qihang.medtrack.ui.medcoach

import com.qihang.medtrack.data.drug.DrugInfo
import com.qihang.medtrack.data.medcoachtip.MedCoachTip

data class MedCoachUiState(
    // ── Drug Information (top half) ──────────────────────────────────
    val drugQuery: String = "",
    /** Logged-in patient's medication names — pre-populates the dropdown. */
    val medicationNames: List<String> = emptyList(),
    val isSearching: Boolean = false,
    val drugInfo: DrugInfo? = null,
    val drugError: String? = null,

    // ── GenAI Tips (bottom half) ─────────────────────────────────────
    val isGeneratingTip: Boolean = false,
    val latestTip: String? = null,
    val tipError: String? = null,
    /** All tips generated by this patient — backs the "Show All Tips" dialog. */
    val allTips: List<MedCoachTip> = emptyList()
)
